### ISSUE TITLE
The Surface Warhead door is bugged

### ISSUE THREAD

**Issue by coco9515** [Faeety/CustomDoorAccess#4]
The Surface Warhead door can be open by the "Containment Engineer Keycard" (ID 6), even if it's not on the list of keycard that can open it.

```yml
cda:
# Enable or disable CustomDoorAccess.
  is_enabled: true
  # Allow or disallow revocation of the access to all the other keycards.
  revoke_all: true
  # Allow or disallow SCPs to open doors that you set with scp_access_doors.
  scp_access: true
  # Gives access to the door with the item(s) that you set.
  access_set:
    NUKE_SURFACE: 8&9&10&11
  # List of the doors that SCPs can open. Only works if door is edited on the access_set config.
  scp_access_doors: []
  # Allow or disallow SCP-079 bypass.
  scp079_bypass: true
  # List of item(s) that are allowed to open the generator doors. (If empty the default keycards will be used)
  generator_access:
  - 7
  - 8
  - 10
  - 11
  # List of item(s) that are allowed to use the elevators. (If empty no access will be set)
  elevator_access: []
```

Small suggestion, while I'm at it : 
Could you had a way to edit which card open the protection to the warhead button on the surface ? and the lever on the inside ?
